add `yjs` extension
prosekit/prosekit pull request #706
Opened 2024-07-24 16:35 UTC by shlroland

add `yjs` extension

The doc for `yjs` is not yet complete.

2024-07-24 18:30 UTC, ocavue commented on packages/extensions/src/yjs/index.ts
> + */
you don't need to add `@internal` if there is no `export`

2024-07-24 18:32 UTC, ocavue commented on packages/extensions/src/yjs/undo-plugin.ts
> +function fixYUnodPlugin(yUndoPluginInstance: ProseMirrorPlugin) {
```suggestion
function fixYUndoPlugin(yUndoPluginInstance: ProseMirrorPlugin) {
```

2024-07-25 00:05 UTC, ocavue commented
First of all, thanks for your contribution. YJS integration is an important feature thus I would need some longer time to review this PR. 

I noticed that the current YJS example requires an appID and token to work. I'm wondering whether if there is an easier way for users to try the collaboration feature.

2024-07-25 01:20 UTC, shlroland commented
> First of all, thanks for your contribution. YJS integration is an important feature thus I would need some longer time to review this PR.
> 
> I noticed that the current YJS example requires an appID and token to work. I'm wondering whether if there is an easier way for users to try the collaboration feature.

The issue here is that in order to fully experience `yjs` online, a server is required to provide a connection service to a `connection provider` like `y-websocket.` Depending solely on the browser itself, one might need to develop a custom provider to simulate the provider's interface within the browser. However, this approach seems impractical as very few people would actually use this provider, apart from showcasing it in documentation. Therefore, as a practical solution, I opted to utilize the cloud service offered by `tiptap cloud`.

2024-07-25 01:40 UTC, shlroland commented
Is it necessary to export the sync, undo, and cursor plugins of Yjs separately? Currently, I have only exported them as a whole using defineYjs.

2024-08-01 12:49 UTC, ocavue commented
> The issue here is that in order to fully experience yjs online, a server is required to provide a connection service to a connection provider like y-websocket. 

I checked yjs's prosemirror example and their provide a public websocket server. This could be a better option for a demo since it doesn't require the user to register a third-party account before using.

2024-08-01 12:52 UTC, ocavue commented
> Is it necessary to export the sync, undo, and cursor plugins of Yjs separately

Let's export the following functions:

- defineYjs
- defineYjsKeymap
- defineYjsCommands
- defineYjsCursorPlugin
- defineYjsUndoPlugin
- defineYjsSyncPlugin

2024-08-01 12:53 UTC, ocavue commented on packages/extensions/package.json
> +    "y-prosemirror": "^1.2.9"
Let's move `y-prosemirror` to `peerDependncies` and also add it in `peerDependenciesMeta`.

2024-08-01 12:57 UTC, ocavue commented on packages/extensions/src/yjs/index.ts
> +function defineSyncPlugin(fragment: Y.XmlFragment, opts?: YSyncOpts) {
Let's put `fragment` into `YSyncOpts` so that this function only has one paramter `options`.

2024-08-01 12:58 UTC, ocavue commented on packages/extensions/src/yjs/index.ts
> +export type YSyncOpts = Parameters<typeof ySyncPlugin>[1]
Let's rename `YSyncOpts` to `YjsSyncOptions`

2024-08-01 13:01 UTC, ocavue commented on packages/extensions/src/yjs/style.css
> +}
What's the purpose of `#y-functions`?

2024-08-06 09:33 UTC, ocavue commented
@shlroland  Hi. Thank you for your work on this PR. Are you planning to continue developing it? If not, I can take over from your current progress.

2024-08-07 03:52 UTC, shlroland commented
> @shlroland Hi. Thank you for your work on this PR. Are you planning to continue developing it? If not, I can take over from your current progress.

Apologies for not being able to update these past two days due to moving. I will make the necessary revisions based on your review suggestions and have them completed by the end of this week.

2024-08-07 12:03 UTC, shlroland commented
Should a mechanism be established to prevent users from adding both history and yjs extension at the same time?

@ocavue

2024-08-08 04:32 UTC, ocavue requested changes

2024-08-08 04:32 UTC, ocavue commented on website/extensions/yjs.md
> +> In this online example, in order to have a complete collaborative experience, you will need to apply for `appId` and `token` from [tiptap cloud](https://cloud.tiptap.dev/).
Let's update the docs since we're not using tiptap cloud anymore in the demo.

2024-08-08 04:32 UTC, ocavue commented on packages/prosekit/package.json
> +    "y-prosemirror": ">= 1.2.9",
```suggestion
    "y-prosemirror": "^1.2.9",
```

2024-08-08 04:32 UTC, ocavue commented on packages/extensions/package.json
> +    "y-prosemirror": ">= 1.2.9",
```suggestion
    "y-prosemirror": "^1.2.9",
```

2024-08-08 04:33 UTC, ocavue requested changes

2024-08-08 04:33 UTC, ocavue commented on playground/examples/react/yjs/extension.ts
> +  return doc && awareness
As an example, maybe we should just enforce `defineExtension` to receive `doc` and `awareness` here?

2024-08-08 04:34 UTC, ocavue commented
> Should a mechanism be established to prevent users from adding both history and yjs extension at the same time?
 
What will happen if users add both `history` and `yjs` extension?

2024-08-08 04:36 UTC, ocavue commented on website/extensions/yjs.md
> +## Usage
Since `yjs` and `y-prosemirror` are peer dependencies, let's add some docs about the installation step.

2024-08-08 04:36 UTC, ocavue commented
@shlroland I left some more review comment. I think we are close to merge it!

2024-08-08 06:57 UTC, shlroland commented
> > Should a mechanism be established to prevent users from adding both history and yjs extension at the same time?
> 
> What will happen if users add both `history` and `yjs` extension?

I tested adding the `yjs` and `history` extensions at the same time, and it did not affect the usage. The default setting for the priority of `yjs` is high, which also ensures the priority use of yjs's undomanager.

2024-08-08 20:59 UTC, ocavue approved these changes
Great! Thanks for your work.

2024-08-08 21:00 UTC, merged